### ISSUE TITLE
Icon color

### ISSUE THREAD

**Issue by angelru** [smetlov/XamarinFormsAndroidBottomMenu#1]
How to change color icon??

**Comment by rc1021** [comment]
@angelru 

it can not change the icon color, because it is become from the image of `./Resources/drawable`

```
# in MainPageRenderer.cs
return new BottomBarTab(Context.Resources.GetDrawable(x.Icon), x.Title);
```

but, you can made icon from customer drawable class, please reference [https://medium.com/@nirinchev/using-icon-fonts-with-xamarin-forms-16da98c98e05](https://medium.com/@nirinchev/using-icon-fonts-with-xamarin-forms-16da98c98e05)

**Comment by avinash-ramireddy** [comment]
There is a work around if you want to show different images(highlighted and not-highlighted).
You can make use of OnAppearing and OnDisappearing to show different images

protected override void OnAppearing (){
//set image source to highlighted image
}
protected override void OnDisppearing (){
//set image source back to not-highlighted image
}

This should be done for each children in tabbed page.

**Comment by hoangwy** [comment]
Try it
private void PopulateBottomBarItems(BottomBar bar, IEnumerable<Page> pages)
        {
            var barItems = pages.Select(x => new BottomBarTab(Context.Resources.GetDrawable(x.Icon), x.Title));
            bar.SetTextAppearance(Resource.Style.bottomBarTextView);
            bar.SetFixedInactiveIconColor(Color.White);
            bar.SetActiveTabColor(Color.Argb(255, 38, 183, 216));
            bar.SetItems(barItems.ToArray());

        }
